"""Native Unlayer reconstructions of the eleven user-supplied email screenshots.
Loaded by generate_template_starters.py; never executes instructions from references.
"""
import struct

def asset(name, pad='0px', maxwidth='100%', align='center'):
 path=OUT/'media'/f'{name}.png'
 width,height=struct.unpack('>II',path.read_bytes()[16:24])
 return {'type':'image','values':{'src':{'url':f'/assets/template-starters/media/{name}.png','width':width,'height':height,'autoWidth':False,'maxWidth':maxwidth},'altText':name.replace('-',' ').capitalize(),'textAlign':align,'containerPadding':pad,'action':{'name':'web','values':{'href':'','target':'_blank'}}}}
def stats(items,bg,ink):
 return {'columns':[[title(value,size=54,font=SERIF,color=ink,align='center',pad='12px 8px'),text(caption,15,ink,align='center',pad='0px 8px 18px')] for value,caption in items],'bg':bg,'pad':'16px 20px'}
def copy(body,**kw): return text(body,**{'size':16,'pad':'12px 30px',**kw})
def reference(key,name,category,description,subject,rows,bg='#F1F1F3',source=None):
 add(key,name,category,description,subject,description,rows,bg=bg,tags=['reference','screenshot',category.lower()])
 TEMPLATES[-1]['reference']=f'user-screenshots/{key}.png'
 TEMPLATES[-1]['source']=source or 'User-supplied screenshot'
 TEMPLATES[-1]['collection']='Reference designs'

reference('webinar-replay','Thanks for Digging In','Events','A coral webinar follow-up with a grocery collage, replay button, resources, and a personal sign-off.','Thanks for cooking with us',[
 row(asset('rge-logo','24px 0px','32%'),bg='#F1F1F3'),
 row(asset('replay-hero'),title('Hi {{first_name}},',size=28,color='#FF5149',pad='32px 26px 4px'),copy('We really appreciated you signing up for <strong>Design Trends 2026: Let’s Get Cooking!</strong> Whether you caught it live or are just getting to this email, we’ve got you covered; <a href="https://example.com/replay">the full replay is ready</a> whenever you want to dig in.'),copy('We covered the design principles behind this year’s biggest email design trends and how to apply that thinking to your own brand, even when a specific trend isn’t the right ingredient for your *dish* (we mean emails—delicious, crunchy emails). If you want to savor a section or share it with your team, the replay’s below.'),button('Catch the replay →','#FF5149',align='center')),
 row(title('Tasty things we talked about from the session:',size=28,pad='20px 26px'),copy('<ul><li><a href="https://example.com/courses">Design Academy Courses</a> (if you want to level up your design skills)</li><li><a href="https://example.com/typography">Golden Ratio Typography Calculator</a></li><li><a href="https://example.com/fonts">Using Custom Fonts</a></li></ul>'),bg='#FFF9F5'),
 row(copy('Have a question we didn’t get to, or want to keep the conversation going? Just reply to this email; we’d love to hear from you.'),copy('Thanks again for spending part of your day with us. We don’t take that for granted.'),title('Cheers,',size=20,color='#CF3E39',align='center'),asset('replay-host','12px 0px','13%'),copy('<strong>Logan & the team</strong>',align='center'),bg='#FFF2F3')
],source='https://reallygoodemails.com/emails/design-trends-webinar-thank-you')
reference('figma-show-work','Show Your Work','Newsletters','A green-and-white editorial with hand-drawn imagery, numbered stories, and an illustrated last word.','An inside look at how we build at Figma',[
 columns([asset('figma-logo','16px 24px','10%',align='left')],[label('A FIGMA NEWSLETTER','#141414',align='right',pad='16px 24px')]),
 row(title('THE<br>LONG AND<br>SHORT OF IT',size=64,color='#0CA95A',align='center',pad='30px 30px 12px'),asset('figma-drawing','20px 75px','100%'),copy('HOW PRODUCTS TAKE SHAPE—AND<br>SHAPE OUR WORLD',align='center'),copy('ISSUE NO.18<br>SHOW YOUR WORK',size=26,align='center',pad='24px 30px'),copy('<em>True collaboration isn’t always comfortable. You have to be willing to share the messy parts of the process—the rough sketches, the unresolved questions—so others can build on those ideas. In that spirit, we’re taking you behind the scenes at Figma to share the human side of building with AI.</em>',pad='16px 54px'),button('GET INTO IT  →','#0CA95A',align='center'),asset('figma-collage')),
 row(copy('<strong>1</strong> &nbsp; Digital tools make it easy to produce something slick—but for Config 2026, our Brand Studio used Figma Make to help create <strong><u>a visual language that was perfectly imperfect.</u></strong>'),divider('#0CA95A'),copy('<strong>2</strong> &nbsp; We’ve all heard how AI is shifting responsibilities, but what does that actually look like? An engineer, designer, and product manager share <strong><u>how building nested folders in Figma gave them a new outlook on their roles.</u></strong>'),divider('#0CA95A'),copy('<strong>3</strong> &nbsp; Product Designer Rogie King was on a mission to bring shaders to Figma—but first, he had to assemble the right team. Here’s what it took to ship these generative tools: an airtight pitch, a prototype-first process, and <strong><u>a passion that was contagious.</u></strong>'),divider('#0CA95A'),copy('<strong>4</strong> &nbsp; We built the AI sentiment index to measure how the industry is changing, how we feel about it, and what it means for the future of design. Researcher Shane Johnston breaks down <strong><u>how AI helped make sense of a huge amount of data.</u></strong>')),
 row(asset('figma-last-word'),copy('There’s more where that came from.<br><a href="https://example.com/stories">Explore Shortcut →</a>',align='center'),bg='#0CA95A')
],bg='#FFFFFF',source='https://reallygoodemails.com/emails/figma-show-work-newsletter')
reference('meet-the-leaders','Meet the Leaders','Newsletters','A vivid blue impact announcement with a portrait collage, a quotation, and stories from the community.','Meet the 155 new Obama Leaders',[
 row(asset('leaders-banner')),
 row(title('{{first_name}},',size=23,pad='24px 45px 8px'),text('The newest class of Obama Leaders is here!',16,font=SERIF,pad='10px 45px'),text('President Obama champions the fundamental belief that change doesn’t come from the top down—it belongs to the next generation of leaders. Through the Obama Leaders Program, an eight-month leadership development initiative, The Obama Foundation equips changemakers ages 25–44 across the government, business, and civil society sectors with values-based leadership skills and a network of support.',16,font=SERIF,pad='10px 45px'),text('Now, 155 leaders from 64 nations and territories will learn from each other, embrace new perspectives, and gain the tools they need to turn hope into action.',16,font=SERIF,pad='10px 45px'),text('<a href="https://example.com/leaders"><strong>Check out their bios and get to know the 2026–2027 Obama Leaders.</strong></a>',16,font=SERIF,pad='10px 45px'),asset('leaders-collage','12px 45px'),button('Meet the Leaders','#111111'),text('Among the 2026–2027 Obama Leaders are:<ul><li>Members of parliament in Germany, Greece, and Türkiye</li><li>A city councillor from Niger</li><li>A municipal court judge in the Philippines</li><li>A social inclusion leader advocating for children’s rights in Albania</li><li>Organizers registering first-time voters in the United States</li></ul>But the power of the Leaders program isn’t in each individual Leader, it’s in the power of bringing them together.',16,font=SERIF,pad='10px 45px'),asset('leaders-quote'),text('And the collaboration won’t end in 2027. Upon completion of the Leaders program, they’ll join the Obama Leadership Network, a growing global alumni community of nearly 1,900 active changemakers across over 160 countries.',16,font=SERIF,pad='24px 45px'),title('EXPLORE LEADER<br>STORIES',size=32,pad='18px 45px')),
 columns([asset('leaders-climate','10px 20px')],[copy('Meet three climate leaders across the Obama Leadership Network.',font=SERIF),label('Learn more →','#111111')]),
 columns([asset('leaders-community','10px 20px')],[copy('How Obama Leader José Patiño went from undocumented to helping thousands of immigrants.',font=SERIF),label('Learn more →','#111111')]),
 columns([asset('leaders-rights','10px 20px')],[copy('Obama Leader and Scholar Nika Kovač advances reproductive rights in Europe.',font=SERIF),label('Learn more →','#111111')]),
 row(copy('The Obama Foundation',color='#FFFFFF'),bg='#0865F4')
],source='https://reallygoodemails.com/emails/obama-foundation-new-leaders-class')
reference('zapconnect','The Great Build-Off','Events','A cream-and-espresso conference invite with an orange video hero, RSVP, and three event metrics.','Get ready for The Great Zapier Build-Off',[
 row(asset('zap-logo','24px 30px','40%',align='left'),bg='#FFFED4'),
 row(copy('Sept 23, 2026 &nbsp; 9:00 a.m. PT &nbsp; Virtual event',color='#F4EDE7',align='center'),title('Get ready for<br>The Great Zapier<br>Build-Off',size=50,color='#F4EDE7',align='center'),asset('zap-film','28px 36px'),copy('This year, we’re adding a big finale to ZapConnect: The Great Zapier Build-Off! Four competitors. Thousands of apps and AI tools. One day. And lots of cameras.',color='#E4DAD4'),copy('Join us live on September 23 as we unveil the winner.',color='#E4DAD4'),copy('Not registered yet? Sign up for ZapConnect today; it’s free.',color='#E4DAD4'),button('Save your spot','#FF4F00',align='center'),divider('#70655E'),title('What to expect at ZapConnect',size=32,color='#F4EDE7',align='center'),bg='#221815'),
 stats([('13k+','expected attendees'),('60+','expert speakers'),('30+','dynamic sessions')],'#221815','#F4EDE7')
],bg='#FFFED4')
reference('greenhouse-welcome','Welcome to MyGreenhouse','Welcome','A clean welcome with a photographic feature banner, four benefits, and a single blue action.','Welcome to MyGreenhouse. Start your search.',[
 row(asset('greenhouse-logo','30px 0px','43%'),bg='#F8F8F8'),
 row(asset('greenhouse-banner'),copy('Hello,',color='#28483F'),copy('MyGreenhouse is your new home for finding roles and following applications—so you can land your next job with less stress.',color='#28483F'),copy('<ul><li><strong>Discover jobs</strong> that meet your needs, like salary, part-time or remote-only.</li><li><strong>Apply faster</strong> with passwordless sign-in and auto-completed applications.</li><li><strong>Get noticed</strong> by marking applications as Dream Jobs.</li><li><strong>Track your progress</strong> by seeing all your application updates in one place.</li></ul>',color='#28483F'),copy('Your next role could be one easy search away.',color='#28483F'),button('Start your search','#367BD7',align='center'))
],bg='#F8F8F8',source='https://reallygoodemails.com/emails/greenhouse-welcome')
reference('most-wanted','August’s Most Wanted','Commerce','A punchy lime-and-forest product spotlight with a bold headline, pack shot, and full-width benefits.','August’s most wanted',[
 row(asset('verb-logo','16px 0px','22%'),bg='#194A28'),
 row(title('AUGUST’S<br>MOST WANTED',size=58,color='#164D26',align='center'),copy('The bars that got the “just one more”<br>treatment. Repeatedly.',size=21,color='#164D26',align='center'),asset('verb-product','24px 44px'),bg='#ACE13A'),
 row(title('We didn’t pick these.<br>We just paid attention.',size=32,color='#164D26',align='center'),copy('Five flavors, no particular order, all equally guilty of showing up as more than “just browsing” can explain. No judges, no voting, no secret sauce. Just a lot of you hitting “add to cart” for the same bars, over and over, like it’s a whole personality trait at this point.',size=21,color='#164D26',align='center'),copy('Call it what it is: a very public confession.',size=21,color='#164D26',align='center'),button('SHOP THE MOST WANTED','#007842',align='center'),bg='#FFFCED'),
 stats([('REAL','INGREDIENTS'),('80MG','ORGANIC CAFFEINE'),('PLANT','BASED')],'#ACE13A','#164D26')
],bg='#F5F5F7')
reference('science-next-gen','Science, Meet Your Next Step','Commerce','Deep teal, electric green typography, an athletic hero, and prominent evidence metrics.','The science behind AG1 Next Gen is real.',[
 row(asset('ag1-logo','26px 30px','20%',align='left')),
 row(title('The science behind<br>AG1 Next Gen is real.',size=48,font=SERIF,color='#8DDF24'),copy('Time to choose how you start.',size=23,color='#E2F0EA'),asset('ag1-cyclist','20px 30px'),bg='#003D3D'),
 stats([('75+','ingredients'),('4','clinical trials'),('60k+','five-star reviews across AG1 products.')],'#003D3D','#E2F0EA'),
 row(copy('You’ve seen the science, read the testimonials, and understand what AG1 Next Gen delivers. The only decision left: choosing which plan fits you best.',size=19,color='#E2F0EA',align='center'),button('Choose My Plan →','#F1EDE7',align='center',ink='#174B42'),bg='#003D3D')
],bg='#FFFFFF')
reference('unleash-the-fizz','Unleashing the Fizz','Commerce','An evergreen product education email with cream FAQ panels, a soda hero, and orange actions.','Unleashing the Fizz',[
 row(asset('olipop-logo','20px 0px','25%'),label('Shop Our Flavors     Store Locator     Subscribe & Save','#004C3D',align='center')),
 row(title('Unleashing<br>the Fizz',size=52,font=SERIF,color='#FFFAE7',align='center'),asset('olipop-fizz','24px 80px'),copy('(Figuratively, of course)',color='#FFFAE7',align='center'),copy('You might be wondering how a soda that’s refreshing and delicious can actually be good for you.',color='#FFFAE7',align='center'),bg='#004C3D'),
 row(title('Our FAQs<br>Will Save the Day',size=34,font=SERIF,color='#004C3D',align='center'),bg='#FFFAE7'),
 row(title('Why is there<br>fiber in OLIPOP?',size=30,font=SERIF,color='#004C3D',align='center'),copy('Fun fact: Most Americans fall short on daily fiber intake, which is why we’ve got your back! With plant fiber, prebiotics, and botanicals, OLIPOP makes it easy to boost digestive and microbiome health.',color='#004C3D',align='center'),bg='#D2E8E2'),
 row(title('What is the<br>difference between<br>a prebiotic and a<br>probiotic?',size=30,font=SERIF,color='#004C3D',align='center'),copy('Simple answer: Prebiotics are the food for probiotics, the “good bacteria.” Our digestive tract hosts many beneficial bacteria that need sustenance, and that’s where prebiotics come in.<br><br>OLIPOP provides clinically tested prebiotics, ensuring gut bacteria get the nutrients they need for overall health.',color='#004C3D',align='center'),bg='#D2E8E2'),
 row(asset('olipop-glass','24px 0px','24%'),title('Let’s Keep Sipping',size=35,font=SERIF,color='#FFFAE7',align='center'),copy('Like saving money? Early access to new flavors? An exclusive help hotline? Score all these things (& more) with an OLIPOP subscription.',color='#FFFAE7',align='center'),button('SIGN UP NOW','#BA6206',align='center'),bg='#004C3D'),
 row(title('Why so<br>Curious?',size=36,font=SERIF,color='#004C3D'),copy('We’ve probably got all your questions covered!',color='#004C3D'),button('EXPLORE FAQS','#004C3D'),bg='#D2E8E2')
])
reference('reading-good-for-you','Reading’s Good for You','Newsletters','A playful soda digest with colorful editorial cards, alternating backgrounds, and rounded calls to action.','Reading’s Good For You',[
 row(asset('olipop-logo','20px 0px','25%'),label('Shop Our Flavors     Store Locator     Subscribe & Save','#004C3D',align='center')),
 row(label('Use code WELCOME15 FOR 15% off your first order','#FFFFFF',align='center'),bg='#007963'),
 row(label('OLIPOP Digest','#004C3D',align='center'),title('Reading’s<br>Good For You',size=44,font=SERIF,color='#004C3D',align='center'),asset('olipop-digest-can','12px 35px'),copy('Hi two birds, one stone by checking out our blog, OLIPOP Digest. It’s not just reading…it’s a dive into all things OLIPOP. Here’s a little appetizer to pique your curiosity…',color='#004C3D',align='center'),bg='#FFFAE7'),
 row(asset('olipop-ice'),title('OLIPOP & Digestive<br>Health: Everything You<br>Need to Know',size=34,font=SERIF,color='#FFFAE7',align='center'),copy('Ever feel like companies toss around health claims like confetti, leaving you uncertain about what’s really in your food and drinks? Well, here’s how we’re different than the other guys and your true partners in wellness.',color='#FFFAE7',align='center'),button('LEARN MORE','#FF5A22',align='center'),bg='#004C3D'),
 row(title('Food and Soda<br>Pairings: What to Eat<br>With OLIPOP',size=34,font=SERIF,color='#004C3D',align='center'),copy('Dive into the food world and explore all the delicious ways to elevate your OLIPOP experience through mouthwatering food pairings. Because when it comes to yumminess, the possibilities are endless…',color='#004C3D',align='center'),button('I’M HUNGRY','#F12339',align='center'),asset('olipop-pairings'),bg='#FFFAE7'),
 row(title('What Is Prebiotic Soda?<br>Knowing the Benefits',size=34,font=SERIF,color='#FFFAE7',align='center'),copy('Consider this the gateway to understanding the magic behind prebiotics and why our sodas are becoming the talk of the town. After this quick read, you’ll find yourself reaching for one off the shelf for more than just our delicious flavor…',color='#FFFAE7',align='center'),button('READ MORE','#FF5A22',align='center'),asset('olipop-flavors'),bg='#004C3D')
],bg='#D2E8E2')
reference('softr-product-update','What’s New in Softr','Product','A clean feature digest with blue and yellow product graphics, compact copy, and an ambassador spotlight.','New in Softr: Item-level sharing + Zoho CRM data source',[
 row(asset('softr-logo','24px 0px','18%'),copy('Hi {{first_name}},<br><br>We’ve been busy making Softr even better.<br><br>Here’s what’s new ↓'),asset('softr-sharing','16px 32px'),title('Item-level sharing',size=25,pad='8px 32px'),copy('Share your Softr apps, databases, and workflows with the right collaborators. We surface connected items too, so sharing an app extends the right permissions to everything linked to it.'),asset('softr-zoho','16px 32px'),title('Zoho CRM data source',size=25,pad='8px 32px'),copy('Zoho CRM is now available as a native data source. Connect your account to build customer portals, client dashboards, and internal tools directly on top of your CRM data.'),asset('softr-integrations','16px 32px'),title('New workflow integrations',size=25,pad='8px 32px'),copy('Bring <strong>SharePoint</strong> into your workflows to manage list items, files, folders, and pages automatically. Kick off a workflow the moment a new <strong>Typeform</strong> is submitted. And connect <strong>QuickBooks</strong> to create and update customers, invoices, vendors, and bills right from Softr.'),title('More updates',size=25,pad='20px 32px 8px'),copy('<strong>App</strong><ul><li>AI can now create apps using your Supabase data</li></ul><strong>Workflow integrations</strong><ul><li>Documint</li><li>Trello</li><li>Tally</li><li>New Stripe actions</li></ul>'),asset('softr-ambassador','20px 32px'),title('Introducing the Softr Ambassador Program',size=25,pad='8px 32px'),copy('<strong>Applications are now open</strong><br><br>If you’ve ever answered a question in the forum, shared a build on social, or told a friend “you have to try Softr” — this is for you.<br><br>We’re selecting a small group of Ambassadors to host local meetups, share what they’re building, and become the person others turn to when they want to build with Softr.'),button('See the program details & apply now','#3E65FF'))
],source='https://reallygoodemails.com/emails/new-softr-item-level-sharing-zoho-crm')
reference('raise-the-standard','Let’s Raise the Standard','Events','A vivid blue advocacy invitation with a parliament hero, a focused message, and a distinctive animal silhouette footer.','Let’s raise the standard',[
 row(asset('rspca-header'),asset('rspca-parliament'),bg='#3524FF'),
 row(title('Let’s raise the standard',size=34,color='#3524FF',pad='18px 22px'),copy('MPs can make a real difference for farmed animals. But we need your help to get them there! On 18 November 2026, we’re hosting an event at the House of Commons. Ask your MP to attend and stand up for animal welfare.',color='#15151A',pad='12px 22px'),button('Invite your MP','#3524FF',align='center'),asset('rspca-animals'),bg='#FFF4E1'),
 row(asset('rspca-logo','16px 0px','30%'),text('The RSPCA is a registered charity in England and Wales, no 219099.<br>RSPCA, Parkside, Chart Way, Horsham, West Sussex RH12 1GY.',12,'#FFFFFF',align='center'),text('Copyright ©RSPCA 2026. All rights reserved.',12,'#FFFFFF',align='center'),bg='#3524FF')
],source='https://reallygoodemails.com/emails/rspca-mp-animal-welfare-invite')

# Additional inspirations: retain the visual rhythm while supplying reusable copy.
reference('connect-your-tools','Connect Your Tools','Welcome','Coral actions, a playful integrations collage, and three practical ways to export your work.','Your next great email starts here',[
 row(title('Your studio',size=23,align='center',pad='20px 30px'),bg='#F1F1F3'),
 row(asset('integrations-hero'),title('Let’s set up your account.',size=30,align='center'),title('So your next great email gets<br>where it needs to go.',size=30,color='#FF5149',align='center',pad='0px 30px 18px'),copy('Hi {{first_name}},<br><br>Connect your sending platform once, then move from a finished design to your next campaign in a few clicks.'),button('Connect your tools','#FF5149',align='center'),title('Your workflow.<br>Your choice of export.',size=29,align='center')),
 columns([asset('integration-html','18px 80px')],[copy('<strong>Copy clean HTML.</strong><br>Take your finished email to the platform your team already uses.')],bg='#F5F3F1'),
 columns([asset('integration-zip','18px 80px')],[copy('<strong>Keep everything together.</strong><br>Download your design and hand it off to a teammate.')],bg='#F5F3F1'),
 columns([asset('integration-pdf','18px 80px')],[copy('<strong>Share a preview.</strong><br>Get feedback before the next send. Good work is a team effort.')],bg='#F5F3F1'),
 row(button('Create your first email','#FF5149',align='center'),copy('Need a hand? Our getting-started guide walks you through every step.',size=14,align='center'))
])
cream='#FBF7ED'; navy='#203D5B'; red='#DB3026'
reference('summer-family-journal','The Family Journal','Newsletters','A long-form cream editorial with a serif masthead, blue section ribbons, reading cards, and a summer recipe.','A little adventure for your summer',[
 row(title('The Family Journal',size=47,font=SERIF,color='#252C33'),label('THE SUMMER ISSUE  /  VOL. 07',navy),copy('Hi {{first_name}},<br><br>Summer has a way of making the everyday feel like an adventure. The days are longer, the plans are looser, and there is always time for one more story.<br><br>This week: a little time outdoors, a small moment of independence, and something cold at the end of a very good day.',font=SERIF),bg=cream),
 row(label('SUMMER FUN','#FFFFFF'),bg=navy),
 row(asset('summer-family'),title('The best family stories<br>start a little off the map.',size=34,font=SERIF,color='#252C33'),copy('A muddy trail. A wrong turn. A picnic that becomes a rain dance. Sometimes the memories that last are the ones you never planned.',font=SERIF),button('READ THE STORY',red,align='center'),title('“The days don’t have to be perfect<br>to become the ones we remember.”',size=35,font=SERIF,color=red,align='center',pad='36px 44px'),asset('summer-child'),title('A little freedom.<br>A whole new world.',size=34,font=SERIF),copy('The first solo ride down the block. The first order at the café. Small acts of independence are big milestones. Here’s how to make room for them.',font=SERIF),button('MAKE ROOM TO GROW',red,align='center'),bg=cream),
 row(label('SUMMER READING','#FFFFFF'),bg=navy),
 *[columns([asset(a,'18px 30px')],[title(h,size=24,font=SERIF,pad='18px 20px 4px'),copy(c,font=SERIF,pad='8px 20px')],bg=cream) for a,h,c in [('summer-ice','The little joys list','Twenty small things to try before the season slips away.'),('summer-adventure','Take the scenic route','Five easy adventures for your next free afternoon.'),('summer-memories','Make this one stick','A few ways to turn good days into lasting memories.')]],
 row(label('REFRESHERS','#FFFFFF'),bg=navy),
 row(asset('summer-refresher'),title('A sunshine slush<br>for the whole table.',size=34,font=SERIF),copy('Citrus, crushed ice, and a little patience. Our favorite alcohol-free summer refresher is as simple as it is good.',font=SERIF),button('GET THE RECIPE',red,align='center'),bg=cream)
],bg=cream)
reference('your-next-teammate','Your Next Teammate','Product','A personal product-trial letter with a blue device hero, pill buttons, and a practical use-case checklist.','Put your next idea to work',[
 row(copy('Hi {{first_name}},<br><br>Your next teammate is ready to meet you.<br><br>Try a new way to make progress on the work that matters. Set a goal, share the context, and keep the decisions in your hands.',pad='32px 36px 8px'),button('Start your free trial','#111111'),asset('bot-workspace','20px 36px'),title('A few things to try first:',size=22),copy('<ul><li><strong>Find your next lead.</strong> Turn research into a focused list of accounts.</li><li><strong>Plan your next page.</strong> Go from a rough brief to a clear outline.</li><li><strong>Tame your inbox.</strong> Surface the messages that need your attention.</li><li><strong>Organize your week.</strong> Bring notes, priorities, and next steps together.</li><li><strong>Help your customers.</strong> Draft thoughtful answers for your team to review.</li></ul>'),copy('Start with one task. See what works. Build from there.<br><br>Your trial is a chance to find a workflow that fits the way you think.'),button('Find your first win','#111111'),copy('Need inspiration? Explore our <a href="https://example.com/guide">quick-start guide</a>.<br><br>Best,<br>The team'))
],bg='#FFFFFF')
# Pill-shaped buttons remain native Unlayer button blocks.
for r in TEMPLATES[-1]['rows']:
 for col in r['columns']:
  for b in col:
   if b['type']=='button': b['values']['borderRadius']='100px'
reference('build-your-first-agent','Build Your First Agent','Events','A gradient-topped workshop invitation with a clear checklist, event card, and recording reminder.','Your first useful agent, in under an hour',[
 row(title('Your workspace',size=22),label('MAKE ROOM FOR THE WORK YOU LOVE','#68717A')),
 row(asset('workshop-gradient'),copy('Hi {{first_name}},<br><br>There’s a task on your list that comes back every week. Copying information. Sorting requests. Chasing the next step.<br><br><strong>Let’s give that task a better home.</strong><br><br>In this hands-on workshop, we’ll build a useful agent together, from first idea to a working example.'),copy('You’ll learn how to:<br><br>✓ Pick a small, specific task worth automating<br><br>✓ Give your agent the right context and boundaries<br><br>✓ Review the result and improve the next run')),
 row(label('JUL 22  /  LIVE WORKSHOP','#DA433F'),title('Your First AI Employee:<br>Build an Agent That Works for You',size=28),copy('50 minutes · Live demo + your questions<br><br><strong>Wednesday, July 22 · 12:00 PM PT / 3:00 PM ET</strong>'),button('Save my seat','#202020',align='center'),bg='#F6F6F8'),
 row(copy('Can’t join live? Register and we’ll send you the recording and a practical playbook after the session.',color='#247EB4',size=15),bg='#EDF6FF')
],bg='#FCFCFD')
reference('meet-your-specialists','Meet Your Specialists','Product','An ivory product update with a two-by-two feature grid, electric-magenta action, and a full-width demo.','Four specialists. One very good team.',[
 row(title('Your studio',size=23),copy('Hi {{first_name}},<br><br>A great result takes more than one perspective. Meet four specialists that help you turn a good brief into something ready for the world.'),bg='#F4F2EE'),
 *[columns([asset(a,'16px 20px'),title(h,size=21,pad='4px 20px'),copy(c,size=15,pad='8px 20px')],[asset(a2,'16px 20px'),title(h2,size=21,pad='4px 20px'),copy(c2,size=15,pad='8px 20px')],bg='#F4F2EE') for a,h,c,a2,h2,c2 in [('specialist-strategy','Strategist · Find the opportunity','Connect the dots between what people need and what your next page should do.','specialist-copy','Copywriter · Sound like you','Shape a message around your real work, your audience, and your voice.'),('specialist-analytics','Analyst · See what works','Understand how people move through your site and where to focus next.','specialist-design','Designer · Keep it together','Refine the layout without losing the system that makes it feel like yours.')]],
 row(button('Meet the specialists','#EC00EB',align='center'),label('WATCH THE DEMO','#D500D3'),title('From a short brief<br>to a live idea.',size=29),asset('specialist-demo'),copy('Find your starting point in our <a href="https://example.com/resources">resource library</a>, or bring a question to the community.<br><br><strong>Let’s make something worth sharing.</strong><br><br>The studio team'),bg='#F4F2EE'),
 stats([('01','A clear brief'),('04','Fresh perspectives'),('∞','Room to create')],'#F4F2EE','#252525')
],bg='#DAD9D4')

reference('digg-tech-digest','Today on Tech','Newsletters','A spare technology digest with a bold lead story, numbered briefs, monospace labels, and an open-source pick.','Five ideas shaping the week in tech',[
 row(copy('Know someone who would enjoy this? <a href="https://example.com/share">Share the edition.</a>',size=13),divider('#E8E8E8'),asset('digg-mark','12px 36px','13%',align='left'),label('TODAY ON /TECH','#5288A6'),copy('A considered look at what builders are paying attention to.',size=16,color='#666666')),
 row(label('TOP STORIES','#5288A6'),title('The next wave of software<br>starts with better questions.',size=37,color='#222222'),copy('New tools can change what is possible. Clear questions help us decide what is useful. This week’s lead story follows teams putting thoughtful evaluation at the heart of their work.',size=19,color='#606060'),label('THE BIG READ  ·  6 MIN','#555555')),
 *[row(title(f'{i} &nbsp; {h}',size=21,pad='22px 36px 4px'),copy(c,size=16,color='#666666',pad='8px 36px'),label('READ THE STORY →','#5288A6')) for i,h,c in [(2,'What teams learn by showing unfinished work','An inside look at prototypes, candid feedback, and the decisions that become better together.'),(3,'Open-source maintainers are building for the long run','The habits and systems that keep a useful project healthy after its first release.'),(4,'A smaller stack can be a stronger foundation','A practical guide to choosing the tools you can support, understand, and improve.'),(5,'The next benchmark is the everyday workflow','Why real tasks tell us something a score alone cannot.')]],
 row(divider('#E8E8E8'),label('ON GITHUB','#5288A6'),label('WHAT THEY’RE BUILDING','#555555'),title('your-org / your-next-project',size=23,font=MONO),copy('Spotlight a project your readers can try, contribute to, or learn from. Add the repository link and explain why it belongs in their toolkit.'),button('Explore the project','#315F7A'),divider('#E8E8E8'),label('THE TECH EDIT  /  YOUR ISSUE DATE','#555555'))
],bg='#FFFFFF',source='https://reallygoodemails.com/emails/digg-tech-newsletter-ai')
reference('zapier-monthly','The Monthly Product Edit','Newsletters','A plum issue header, three grid-backed feature stories, paired articles, a lilac event spotlight, and compact app news.','Good work deserves a better workflow',[
 row(asset('zapier-mark','16px 36px','22%',align='left')),
 row(label('YOUR MONTHLY EDITION','#E8DDE8',align='center'),title('Your latest, all together.',size=34,color='#FFFFFF',align='center'),copy('Useful updates for the people making things happen.',color='#E8DDE8',align='center'),bg='#391B34'),
 row(title('What’s new',size=26),asset('zapier-guided','18px 36px'),title('Turn a great workflow into a repeatable one.',size=25),copy('The smartest process on your team should be easy to share. Package the steps, add context, and give the next person a clear place to begin.'),button('Create a shared template →','#241916'),asset('zapier-mcp','18px 36px'),title('Give your tools a little more context.',size=25),copy('Bring the right information to the right step. Connected tools work better when the handoff is clear and your team stays in control.'),button('Explore the connections →','#241916'),asset('zapier-tables','18px 36px'),title('One home for the work behind the work.',size=25),copy('Keep the details that power your process together. Fewer places to look. More time to move things forward.'),button('Take a closer look →','#241916')),
 row(title('Featured articles',size=26),bg='#C8C4B3'),
 columns([asset('zapier-security','16px 20px'),title('Share with intention.',size=23,pad='8px 20px'),copy('A practical guide to the information your tools need—and the details they don’t.',size=15,pad='8px 20px')],[asset('zapier-skills','16px 20px'),title('Make knowledge usable.',size=23,pad='8px 20px'),copy('Turn a hard-won lesson into a resource your whole team can put to work.',size=15,pad='8px 20px')],bg='#C8C4B3'),
 row(title('In the spotlight',size=26),asset('zapier-spotlight','16px 36px'),title('Good ideas, in good company.',size=27),copy('Join our next live gathering for honest conversations, practical demos, and a few new perspectives.'),button('See the event →','#391B34'),bg='#F1E7F1'),
 row(title('New & noteworthy',size=26),copy('<strong>01 / Clearer handoffs</strong><br>A simple way to keep the next step visible.'),divider(),copy('<strong>02 / Better meeting notes</strong><br>Turn a conversation into decisions your team can find.'),divider(),copy('<strong>03 / Your next useful shortcut</strong><br>A small improvement that earns its place every day.')),
 row(title('Keep building.',size=32,color='#FFFFFF'),copy('A question, a suggestion, a good idea?<br>We’d love to hear from you.',color='#E9DDD5'),bg='#241916')
],bg='#EDEBE5')

reference('animal-facts-pistol-shrimp-quiz','Small Animal, Big Sound','Newsletters','A forest-green science digest with a photographic lead, four-answer quiz, and related reading.','A tiny shrimp creates one of the ocean’s loudest sounds',[
 row(title('Animal Facts',size=32,color='#E0E765',align='center'),bg='#1A4934'),
 row(label('FACT OF THE DAY  /  ACROSS SPECIES','#4B5C2B'),title('A tiny shrimp creates one of the ocean’s loudest sounds.',size=33),copy('By the Animal Facts editors',size=13),asset('animal-shrimp','18px 30px'),copy('Pistol shrimp are small, but their oversized snapping claw creates a powerful jet of water. The jet forms a bubble that collapses with a sharp sound—a remarkable example of the physics hiding in the natural world.'),copy('The snap helps the shrimp hunt and communicate. Follow the story to learn how researchers study this tiny animal and the surprisingly noisy world beneath the surface.'),button('Hear the whole story →','#1A4934')),
 row(label('TODAY’S QUESTION','#1A4934'),title('Which is NOT a crustacean?',size=28)),
 columns([button('MUSSEL','#E9ECE7',ink='#20382A',href='https://example.com/quiz?answer=mussel')],[button('LOBSTER','#E9ECE7',ink='#20382A',href='https://example.com/quiz?answer=lobster')]),
 columns([button('SHRIMP','#E9ECE7',ink='#20382A',href='https://example.com/quiz?answer=shrimp')],[button('CRAB','#E9ECE7',ink='#20382A',href='https://example.com/quiz?answer=crab')]),
 row(title('Keep exploring',size=25,color='#1A4934'),divider(),title('What’s the loudest animal on Earth?',size=23),divider(),title('Do shrimp eat other shrimp?',size=23),divider(),title('What qualifies as a crustacean?',size=23)),
 row(title('Stay curious.',size=36,color='#E0E765',align='center'),copy('A little wonder, delivered regularly.',color='#FFFFFF',align='center'),bg='#1A4934')
],bg='#F6F5ED',source='https://reallygoodemails.com/emails/animal-facts-pistol-shrimp-quiz')
reference('book-next-international-trip-us','The International Golf Trip','Commerce','An ivory-and-yellow travel email with a scenic lead, destination map, and a photographic trip-planning panel.','Book your next international golf trip',[
 row(title('Fried Egg Golf',size=30,font=SERIF,align='center'),asset('golf-landscape','18px 24px'),title('BOOK YOUR NEXT<br>INTERNATIONAL TRIP',size=35,align='center'),copy('A great golf trip starts long before the first tee. Discover memorable courses, thoughtful places to stay, and a route that leaves time to enjoy the journey.',font=SERIF,size=19,align='center'),button('PLAN YOUR TRIP','#FFEE56',ink='#191919',align='center'),bg='#F3F0E7'),
 row(divider('#817C70'),asset('golf-map','18px 24px'),title('WHERE WE GO',size=32,align='center'),copy('Explore Great Britain and Ireland, from celebrated courses to quieter discoveries. Focus on a region or two and spend more of your trip where you want to be.',font=SERIF,size=19,align='center'),copy('Tell us the places you have in mind, the kind of golf you enjoy, and who is coming along. We’ll help you start planning a trip with a little more local perspective.',font=SERIF,size=19,align='center'),button('EXPLORE DESTINATIONS','#FFEE56',ink='#191919',align='center'),asset('golf-collage','18px 24px'),button('LET’S GET STARTED','#FFEE56',ink='#191919',align='center'),bg='#F3F0E7')
],bg='#FFFFFF',source='https://reallygoodemails.com/emails/book-next-international-trip-us')
for rr in TEMPLATES[-1]['rows']:
 for cc in rr['columns']:
  for bb in cc:
   if bb['type']=='button':bb['values']['borderRadius']='100px';bb['values']['size']['autoWidth']=False
